service: serverless-boilerplate

provider:
  name: aws
  runtime: python2.7

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: GET
          cors: true
