service: serverless-boilerplate

provider:
  name: aws
  runtime: python2.7

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
          cors: true

resources:
  Outputs:
    ServiceEndpoint:
      Export: serverless-boilerplate-${stage}-ServiceEndpoint