service: serverless-boilerplate

provider:
  name: aws
  runtime: python2.7

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
          cors: true

resources:
  Outputs:
    #  this feels like a hack: see https://github.com/s0enke/cloudformation-templates/issues/2
    ServiceEndpoint:
      Export:
        Name: serverless-boilerplate-${self:provider.stage}-ServiceEndpoint